### PR TITLE
Enforce Android-SDK in flake devShell

### PR DESCRIPTION
**Pull request by MatthewCroughan**
Adds a devShell capable of enforcing the correct android-sdk,
debug.keystore and godot-export-templates. All anyone has to do to
develop tunnelvr now is `nix develop`

This patches Godot's C++ source code to use envvars to get the path to
various tools, rather than looking it up in
`~/.config/godot/editor_settings-3.tres`

### CODE REVIEW

**Review by goatchurchprime — APPROVED** [review]
yeah it worked on my machine

**Comment by bezark** [comment]
Hey @MatthewCroughan ! This project looks really neat. 3 years later I'm running into similar issues trying to get godot and android to play nice. Do you think this approach works for godot 4.3?

**Comment by goatchurchprime** [comment]
@bezark this is what I am currently running with (as `nix develop`)
 [flake.zip](https://github.com/user-attachments/files/16927602/flake.zip)
It would be neat to have a flake that also built the android templates instead of downloading them, but this works.

**Comment by bezark** [comment]
Wow thanks so much! This is very helpful

**Pull request merged**
